### ISSUE TITLE
IRobotMotion Class Missing

### ISSUE THREAD

**Issue by yunusdawji** [FellowRoboticists/RobotMediator#1]
Error:(22, 5) error: cannot find symbol class IRobotMotion

**Comment by naiveroboticist** [comment]
I'm sorry this is all so poorly documented and put together. There is a library used by this project that provides the IRobotMotion class among others. You can find this library at: https://github.com/FellowRoboticists/SensorPacketReaderTools

Hope this helps.

**Comment by yunusdawji** [comment]
Thanks a lot!
